# Generated by Django 4.2.3 on 2023-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submisssions/images'),
        ),
    ]
