# Generated by Django 4.2.3 on 2023-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonapp', '0002_submission_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='submissions/images'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/file'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
