# Generated by Django 4.2.3 on 2023-08-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonapp', '0003_alter_submission_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='image',
            new_name='submission_image',
        ),
    ]
