# Generated by Django 4.2.3 on 2023-08-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathonapp', '0004_rename_image_submission_submission_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submission_image',
        ),
    ]
